### ISSUE TITLE
Button should disabled

### ISSUE THREAD

**Issue by regan-jiang** [detrust-finance/frontend#14]
When there is no data, the button should be disabled
![image](https://user-images.githubusercontent.com/70511020/129320146-be0fdaeb-f41f-463c-bb81-05ab26f7687c.png)

**Comment by AndyChenW** [comment]
thanks @regan-jiang

**Comment by rok4f** [comment]
thanks @regan-jiang, it's fixed in #11

**Comment by AndyChenW** [comment]
just deployed, sorry the repo is renamed before and not deployed
automatically, now it's deployed

Web Ninja ***@***.***> 于2021年8月16日周一 上午10:19写道：
