### ISSUE TITLE
your-account seems not a good path

### ISSUE THREAD

**Issue by AndyChenW** [detrust-finance/frontend#2]
need a better path name

**Comment by rok4f** [comment]
Any suggestion to the alternative?

**Comment by AndyChenW** [comment]
I think that [dashboard] or [trust-list] would be better, what do you think? but I am sure that [your-account] is not so good naming.

**Comment by rok4f** [comment]
"dashboard" is ok

**Comment by AndyChenW** [comment]
Fine.

**Comment by rok4f** [comment]
done
